prometheus:
  alertmanager:
    enabled: true
  pushgateway:
    enabled: true
  prometheus-node-exporter:
    enabled: true
    hostNetwork: false
    hostPID: false
    securityContext:
      runAsUser: 0
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
      extraArgs:
      collector.logfiles.path: "/var/log/docker/containers"  # แก้ไขเป็น key-value
      no-collector.textfile: true - --collector.logfiles.path=/var/log/docker/containers
      
grafana:
  adminPassword: 'sarawut2001'
  service:
    type: NodePort
    nodePort: 30000

serviceMonitorSelector:
  matchLabels:
    release: prometheus

additionalServiceMonitors:
  - name: kubernetes-service-endpoints
    selector:
      matchExpressions:
        - key: k8s-app
          operator: Exists
    namespaceSelector:
      any: true
    endpoints:
      - port: metrics
        interval: 30s
