prometheus:
  alertmanager:
    enabled: true
  pushgateway:
    enabled: true
  prometheus-node-exporter:
    enabled: true
    hostNetwork: false
    hostPID: false
    securityContext:
      runAsUser: 0
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
      
grafana:
  adminPassword: 'sarawut2001'
  service:
    type: NodePort
    nodePort: 30000
