apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nodejs
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics